services:
  app:
    build:
      context: .
    container_name: exchangerate

    ports:
      - "8080:8080"
  redis:
    image: "redis:7.4.2"
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis_password
